#!/bin/sh
# -- 絶対パスを取得
MyPath=$(cd $(dirname $0);pwd)
# -- 共通設定をインクルード
. ${MyPath}/getmybase
DATE=`date +%w`
cd ${RootPath}/app
# --- 本番↓
php ${RootPath}/app/Console/cake.php FileDelete  >> ${DataPath}/tmp/${MyBaseFile}_cleanup_${DATE}.log -app ${RootPath}/app