#!/bin/sh

# -- 絶対パスを取得
MyPath=$(cd $(dirname $0);pwd)

# -- 共通設定をインクルード
. ${MyPath}/getmybase

DATE=`date +%w`
cd ${RootPath}/app

# --- 本番↓
${RootPath}/app/Console/cake SendNotice  >> ${DataPath}/tmp/${MyBaseFile}_sendnotice_${DATE}.log -app ${RootPath}/app
#${RootPath}/app/Console/cake SendNotice --max $1 -app ${RootPath}/app
