#!/bin/sh

# -- 絶対パスを取得
MyPath=$(cd $(dirname $0);pwd)

# -- 共通設定をインクルード
. ${MyPath}/getmybase

DATE=`date +%w`
cd ${RootPath}/app
${RootPath}/app/Console/cake VersionUp $1 $2 $3 $4 $5  >> ${DataPath}/tmp/${MyBaseFile}_versionup_${DATE}.log -app ${RootPath}/app

